<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-W8fXfP3gkOKtndU4JGtKDvXbO53Wy8SZCQHczT5FMiiqmQfUpWbYdTil/SxwZgAN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.min.js" integrity="sha384-skAcpIdS7UcVUC05LJ9Dxay8AXcDYfBJqt1CJ85S/CFujBsIzCIv+l9liuYLaMQ/" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="index.css">
</head>
<body>
    <form class="card" action="remove.php" method="get">
        <section><img src="xz5ng8.svg" alt="">
        <h2 class="card-title">Ma TODOLIST </h1></section>
        <ul class="list-group">
        <?php foreach($lines as $key=> $line): ?>
        <div class="form-check form-switch  card-body">
        <input class="form-check-input" type="checkbox" name="index[]" value="<?=$key;?>" id="">
        <?php if($line[3]=='basse'): ?>
            <li class="list-group-item list-group-item-dark">
            <label class="titre" for=""><?= $line[0];?></label>
            <br>
            <label class="description" for=""><?= $line[1];?></label>
            <br>
        </li>
        <?php elseif ($line[3]=='normale'):?>
        <li class="list-group-item list-group-item-success">
            <label class="titre" for=""><?= $line[0];?></label>
            <br>
            <label class="description" for=""><?= $line[1];?></label>
            <br>
        </li>
        <?php elseif ($line[3]=='haute'):?>
        <li class="list-group-item list-group-item-danger">
            <label class="titre" for=""><?= $line[0];?></label>
            <br>
            <label class="description" for=""><?= $line[1];?></label>
            <br>
        </li>
        <?php endif;?>
        </div>
        
        
        <?php endforeach;?></ul>
        <?php if(!empty($lines)): ?>
        <button type="submit" class="btn btn-warning">Supprimer</button>
        <?php endif;?>   
    </form>
    <hr>
    <form class="card" action="add.php" method="get">
    <section><img src="lt9vo.svg" alt="">
    <h2 class="card-title">>Nouvelle tache</h2></section>
        
        <label for="">Titre </label>
        <input class="form-control form-control-lg" type="text" name="titre">
        <br>
        <label for="">Description </label>
        <textarea class="form-control form-control-lg" name="description" id="" cols="30" rows="10"></textarea>
        <br>
        <label for="">Date de fin </label>
        <div class="date">
        <select class="form-select" name="jour" id="">
            <?php for($i=1;$i<32;$i++):?>
            <option value="<?=$i;?>"><?=$i;?></option>
            <?php endfor;?>
        </select>
        <select class="form-select" name="mois">
            <option value="Janvier">Janvier</option>
            <option value="février">février</option>
            <option value="mars">mars</option>
            <option value="avril">avril</option>
            <option value="mai">mai</option>
            <option value="juin">juin</option>
            <option value="juillet">juillet</option>
            <option value="aout">aout</option>
            <option value="septembre">septembre</option>
            <option value="octobre">octobre</option>
            <option value="novembre">novembre</option>
            <option value="décembre">décembre</option>
        </select>
        <select class="form-select" name="annee" id="">
            <?php for($i=0;$i<7;$i++):?>
            <option value="<?=date('Y')+$i;?>"><?=date('Y')+$i;?></option>
            <?php endfor;?>
        </select>
        </div>
        <br>
        <label for=""><strong>Priorité</strong>  </label>
        <br>
        <div class="form-check">
        <input class="form-check-input" id="check1" type="radio" name="pr" value="basse" checked>
        <label class="form-check-label" for="check1">Basse </label>
        <br>
        </div>
        <div class="form-check">
        <input class="form-check-input" id="check2" type="radio" name="pr" value="normale">
        <label class="form-check-label" for="check2">Normale </label>
        <br>
        </div>
        <div class="form-check">
        <input class="form-check-input" id="check3" type="radio" name="pr" value="haute">
        <label class="form-check-label" for="check3">Haute </label>
        <br>
        </div>
        <button type="submit" class="btn btn-success">Enregistrer</button>
    </form>
    <script src="index.js"></script>
</body>
</html>